[package]
name = "language_model"
version = "0.1.0"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
edition = "2021"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
indexmap = { version= "1.6", features = ["serde-1"]}
bincode = "1.3"
flate2 = "1.0"
